# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('teaser', models.CharField(blank=True, max_length=255, verbose_name='First part of the body')),
                ('reddit_id', models.CharField(max_length=64)),
                ('pub_date', models.DateTimeField(verbose_name='When it was published on Reddit')),
                ('score', models.IntegerField(default=0, verbose_name='Reddit Score')),
            ],
        ),
    ]
