# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NerdBaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='What are they called on Reddit?')),
                ('known_as', models.CharField(max_length=255, verbose_name='The name / speeling they are most commonly known by')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='nerdballer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.NerdBaller'),
            preserve_default=False,
        ),
    ]
