# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_permalink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nerdballer',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='What are they called on Reddit?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reddit_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
