# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nerdballer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subreddit',
            field=models.CharField(default='', max_length=255, verbose_name='The subreddit where this submission was posted'),
            preserve_default=False,
        ),
    ]
